segmentation:
  pupil:
    dp: 1
    minDist: 1000
    param1: 150
    param2: 20
    minRadius: 10
    maxRadius: 200
    canny_threshold_1: 75
    canny_threshold_2: 250

  iris:
    dp: 2
    minDist: 1000
    param1: 150
    param2: 20
    minRadius: 40
    maxRadius: 100
    canny_threshold_1: 25
    canny_threshold_2: 100

  alpha: 0.0
  beta: 1.0
  gamma: 0
  padded_x_size: 1200
  padded_y_size: 1200
  final_x_size: 250
  final_y_size: 250

normalization:
  x_size: 64
  y_size: 512
  border: 48

gabor_filter:
  x_size: 21
  y_size: 21
  gamma: 0.6
  frequency: 0.5
  sigma: 0.4
  psi: 0

feature_reduction_lle:
  n_neighbors: 215
  n_components: 215

matching:
  lowe_filter: 0.88
  stdev_r_diff: 0.15
  stdev_theta_diff: 10
  threshold: 22

training:
  nn:
    want_to_use_cuda: true
    lower_is_better: true
    evaluation_metric: 'accuracy'
    batch_size: 32
    lr: 0.01
    num_epochs: 500
